import { MetadataRoute } from 'next'

const BASE_URL = 'https://www.onlinebrandgrowth.com'

// All blog post slugs (matching the existing posts array in blog/page.tsx)
const blogSlugs = [
  'what-is-fulfillment-by-amazon',
  'product-information-management',
  'sponsored-ad-amazon',
  'amazon-backend-keywords',
  'can-you-use-coupons-on-amazon',
  'what-is-frustration-free-packaging',
  'seller-fulfilled-prime-fulfillment',
  'amazon-brand-guide',
  'amazon-channel-management',
  'ecommerce-conversion-rates',
  'image-guidelines-amazon',
  'inventory-turnover-ratio-explained',
  'amazon-vendor-vs-seller',
  'how-much-does-amazon-charge-to-sell',
  'amazon-storefront-design',
  'suspended-from-amazon',
  'ecommerce-account-management',
  'what-is-an-amazon-storefront',
  'amazon-brand-protection-services',
  'amazon-ppc-agency-pricing',
  'how-to-calculate-contribution-margin',
  'amazon-fba-fees',
  'amazon-listing-optimisation',
  'brand-registry-amazon',
  'photography-for-amazon',
  'what-does-acos-stand-for',
  'create-an-amazon-storefront',
  'prep-center-fba',
  'minimum-advertised-price-monitoring',
  'how-to-make-an-amazon-storefront',
  'amazon-product-photography',
  'acos-in-amazon',
  'what-does-map-mean-in-pricing',
  'digital-shelf-analytics',
  'ecommerce-growth-strategies',
  'amazon-fba-freight-forwarders',
  'amazon-suspending-accounts',
  'amazon-seller-central-vs-vendor-central',
  'amazon-advertising-strategy',
  'brand-protection-amazon',
  'what-is-frustration-free-packaging-on-amazon',
  'product-photography-for-amazon',
  'amazon-fba-vs-fbm',
  'find-amazon-keywords',
  'amazon-pricing-strategy',
  'fba-freight-forwarder',
  'sell-on-amazon-worldwide',
  'freight-forwarder-for-amazon-fba',
  'account-suspension-amazon',
  'map-vs-msrp',
  'amazon-brand-store',
  'inventory-management-best-practices',
  'amazon-images-requirements',
  'amazon-deactivated-seller-account',
  'msrp-vs-map',
  'amazon-account-suspended',
  'product-photography-amazon',
  'best-amazon-storefronts',
  'listing-optimization-on-amazon',
  'amazon-account-suspensions',
  'freight-forwarders-for-amazon-fba',
  'amazon-brand-stores',
  'listing-optimization-amazon',
  'amazon-advertising-strategies',
  'map-vs-msrp-price',
  'track-amazon-ranking',
  'amazon-brand-guidelines',
  'amazon-ppc-management-services',
  'amazon-listing-optimization',
  'amazon-fba-is-it-worth-it-2',
  'suspended-amazon-account',
  'amazon-ad-management',
  'how-to-increase-amazon-sales',
  'product-launch-strategies',
  'optimizing-amazon-listings',
  'global-selling-with-amazon',
  'account-suspended-amazon',
  'optimizing-amazon-product-listings',
  'optimize-amazon-product-listings',
  'improve-amazon-sales',
  'increase-amazon-sales',
  'how-to-improve-amazon-sales',
  'target-market-for-amazon',
  'how-to-launch-product-on-amazon',
  'what-is-frustration-free-packaging-at-amazon',
  'freight-forwarder-amazon-fba',
  'ship-from-china-to-amazon-fba',
  'amazon-brand-registry-benefits',
  'what-is-amazon-brand-registry',
  'best-amazon-inventory-management-software',
  'amazon-account-suspension',
  'unauthorized-sellers-on-amazon',
  'how-to-win-amazon-buy-box',
  'amazon-fba-profit-margin-calculator',
  'map-pricing-vs-msrp',
  'minimum-advertised-price-policy',
  'amazon-pricing-changes',
  'cost-of-selling-on-amazon',
  'amazon-pricing-strategies',
  'amazon-dsp-advertising',
  'acos-on-amazon',
  'amazon-ads-management',
  'image-requirements-for-amazon',
]

export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date()

  // Core pages
  const staticPages: MetadataRoute.Sitemap = [
    {
      url: BASE_URL,
      lastModified: now,
      changeFrequency: 'weekly',
      priority: 1.0,
    },
    {
      url: `${BASE_URL}/services`,
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.9,
    },
    {
      url: `${BASE_URL}/case-studies`,
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.9,
    },
    {
      url: `${BASE_URL}/360-brand-protection`,
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/blog`,
      lastModified: now,
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/media`,
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: `${BASE_URL}/careers`,
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.5,
    },
    {
      url: `${BASE_URL}/privacy`,
      lastModified: now,
      changeFrequency: 'yearly',
      priority: 0.3,
    },
    {
      url: `${BASE_URL}/terms`,
      lastModified: now,
      changeFrequency: 'yearly',
      priority: 0.3,
    },
  ]

  // Blog post pages — pointing to the old domain for now since articles live there
  // TODO: migrate blog posts to this domain as new articles are written
  const blogPages: MetadataRoute.Sitemap = blogSlugs.map((slug) => ({
    url: `${BASE_URL}/blog/${slug}/`,
    lastModified: now,
    changeFrequency: 'monthly' as const,
    priority: 0.6,
  }))

  return [...staticPages, ...blogPages]
}
